### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLastBufferRow' of undefined

### ISSUE THREAD

**Issue by stelek** [mrkschan/ctags-status#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ctags-status](https://github.com/mrkschan/ctags-status) package, v1.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getLastBufferRow' of undefined

```
At /Users/stelek/.atom/packages/ctags-status/lib/scope-finder.coffee:7

TypeError: Cannot read property 'getLastBufferRow' of undefined
  at Object.module.exports.guessedTagEnd (/Users/stelek/.atom/packages/ctags-status/lib/scope-finder.coffee:7:22)
  at explode (/Users/stelek/.atom/packages/ctags-status/lib/ctags-status.coffee:151:27)
  at /Users/stelek/.atom/packages/ctags-status/lib/ctags-status.coffee:155:17
  at /Users/stelek/.atom/packages/ctags-status/lib/ctags-status.coffee:195:15
  at /Users/stelek/.atom/packages/ctags-status/lib/ctags.coffee:35:7
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:137:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:149:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter",
      "linter-clang",
      "symbols-view"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "audioBeep": false,
    "ignoredNames": [
      "build",
      "tags"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-ctags, v3.0.2
auto-detect-indentation, v0.4.0
autocomplete-clang, v0.6.5
autocomplete-plus, v2.12.0
ctags-status, v1.2.0
docblockr, v0.6.3
monokai, v0.14.0
reveal-active-file-context, v0.2.0
symbols-tree-view, v0.9.2
tree-view-git-projects, v0.5.0

# Dev
No dev packages
```

**Comment by mrkschan** [comment]
Guessing this can be reproduced by switching from file to non-file within 500ms (before Ctags finish processing the file). Need further investigation to really reproduce the reported issue.

**Comment by stelek** [comment]
I think it happened after I chose "Close all tabs" from a menu.

**Comment by mrkschan** [comment]
yea, i can reproduce that now. thx :)

**Comment by mrkschan** [comment]
Reproduce:
1. Open workspace with a few already 'opened' files.
2. Close all tabs.

Cause:

Guessing each "tab close" in Atom actually "opens" the file in a text editor and "closes" that immediately. Thus, activating Ctags on editor open but no text editor is found when Ctags finish processing.
