### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by VoltairesPuppet** [mrkschan/ctags-status#18]
[Enter steps to reproduce below:]
1. Installed CTAGS for windows and restarted atom
2. Open up any C++ source or header file 
3. Exception thrown and no ctag related information provided 

**Atom Version**: 0.200.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [ctags-status](https://github.com/mrkschan/ctags-status) package, v1.2.4
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At C:\Users\ahefford\.atom\packages\ctags-status\lib\ctags.coffee:14

TypeError: Cannot read property 'split' of undefined
  at parse (C:\Users\ahefford\.atom\packages\ctags-status\lib\ctags.coffee:14:34)
  at C:\Users\ahefford\.atom\packages\ctags-status\lib\ctags.coffee:22:13
  at Ctags.module.exports.Ctags.parseTags (C:\Users\ahefford\.atom\packages\ctags-status\lib\ctags.coffee:35:9)
  at C:\Users\ahefford\.atom\packages\ctags-status\lib\ctags.coffee:35:15
  at Socket.<anonymous> (C:\Users\ahefford\AppData\Local\atom\app-0.200.0\resources\app.asar\src\buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```
### Commands

```
     -8:33 core:cancel (div.settings-view.pane-item)
     -6:31.6.0 grammar-selector:show (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "ctags-status": {
    "outerScope": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-terminal-panel, v4.4.4
block-travel, v1.0.2
color-picker, v1.7.0
crosshairs, v0.1.2
ctags-status, v1.2.4
docblockr, v0.7.1
linter, v0.12.4
mark-ring, v3.0.0
minimap, v4.9.0
project-manager, v1.15.5
Sublime-Style-Column-Selection, v1.2.3

# Dev
No dev packages
```

**Comment by mrkschan** [comment]
Hey @VoltairesPuppet  please give v1.2.5 a try. Thx for reporting :)
