### ISSUE TITLE
Uncaught Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by paradox460** [mrkschan/ctags-status#32]
**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [ctags-status](https://github.com/mrkschan/ctags-status) package, v1.3.4
### Stack Trace

Uncaught Error: spawn ENAMETOOLONG

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Ctags.module.exports.Ctags.generateTags (/Users/jsandberg/.atom/packages/ctags-status/lib/ctags.coffee:47:22)
    at Object.module.exports.CtagsStatus.toggle (/Users/jsandberg/.atom/packages/ctags-status/lib/ctags-status.coffee:180:14)
    at /Users/jsandberg/.atom/packages/ctags-status/lib/ctags-status.coffee:83:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:316:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:494:18
    at process._tickCallback (node.js:368:9)
```
### Commands

```
     -9:19.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:19.2.0 blur (atom-text-editor.editor.mini.is-focused)
     -9:19 git-blame:toggle (atom-text-editor.editor.vim-mode-plus.insert-mode)
     -9:16.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -9:16.4.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -9:14.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:14.9.0 blur (atom-text-editor.editor.mini.is-focused)
     -9:14.9.0 open-on-github:blame (atom-text-editor.editor.vim-mode-plus.insert-mode)
  2x -9:14.9.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -8:31.8.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  3x -8:31.3.0 vim-mode-plus:toggle-fold (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -6:45.9.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:02.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:02.5.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:00.5.0 blur (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "quantum-ui",
      "base16-tomorrow-dark-theme"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "save-session",
      "emacs-flow",
      "autocomplete",
      "feedback",
      "deprecation-cop",
      "ruby-string-interpolation"
    ],
    "packagesWithKeymapsDisabled": [
      "highlight-line",
      "whitespace",
      "notifications"
    ]
  },
  "ctags-status": {
    "outerScope": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mrkschan** [comment]
Hey @paradox460, did you try v1.3.4 and set your ctags executable path in the settings?

**Comment by mrkschan** [comment]
And, @paradox460, would you mind telling me how many characters are there on the filepath of the file being opened?

**Comment by paradox460** [comment]
Setting the ctags executable seemed to fix the issue. Thanks!

**Comment by mrkschan** [comment]
I looked around the web and many suggested that the cause is having a very long file path in the CLI call. May I know if you can confirm this? Either your path to the ctag executable or the path of the file being edited would be longer than that of nodejs is allowed.

On Tue, Jan 12, 2016 at 11:12 AM -0800, "Jeff Sandberg" notifications@github.com wrote:

Setting the ctags executable seemed to fix the issue. Thanks!

**Comment by paradox460** [comment]
My ctags executable is at a fairly standard location, `/usr/local/bin/ctags`

The filename wasn't exceptionally long either, the absolute path is only 76 characters long
