### ISSUE TITLE
Uncaught TypeError: Cannot read property 'repo_name' of undefined

### ISSUE THREAD

**Issue by shelbyKiraM** [mrkschan/ctags-status#45]
1. Open directory that has no repo
2. Git error!
3. Get error.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.4
**Thrown From**: [ctags-status](https://github.com/mrkschan/ctags-status) package 1.3.7

### Stack Trace

Uncaught TypeError: Cannot read property 'repo_name' of undefined

```
At /Users/user/.atom/packages/ctags-status/node_modules/q/q.js:155

TypeError: Cannot read property 'repo_name' of undefined
    at StatusBarView.setProfile (/packages/my-github-profile/lib/main.coffee:57:62)
    at setProfile (/packages/my-github-profile/lib/main.coffee:116:25)
    at /packages/my-github-profile/lib/main.coffee:126:11
    at _fulfilled (/packages/ctags-status/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/packages/ctags-status/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/packages/ctags-status/node_modules/q/q.js:796:13)
    at /packages/ctags-status/node_modules/q/q.js:604:44
    at runSingle (/packages/ctags-status/node_modules/q/q.js:137:13)
    at flush (/packages/ctags-status/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -7:05.7.0 core:select-right (input.hidden-input)
     -7:03.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-ctags 5.1.2 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atomic-chrome 0.3.3 
auto-indent 0.5.0 
autocomplete-ctags 0.4.1 
base16-tomorrow-night-eighties-syntax 0.12.0 
browser-refresh 0.9.0 
busy-signal 1.4.3 
case-conversion 0.2.0 
color-picker 2.2.5 
ctags-status 1.3.7 
debug 0.0.1 
dict 0.3.1 
editorconfig 2.2.2 
emmet 2.4.3 
environment 1.3.1 
file-type-icons 1.3.4 
file-types 0.5.5 
fold-functions 0.5.0 
git-control 0.9.0 
git-diff-details 1.4.0 
go-config 1.2.4 
hard-wrap 1.7.1 
Hyrule-atom 1.2.1 
intentions 1.1.5 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.6.10 
marked 0.1.10 
material 2.2.0 
material-ui 1.0.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
my-github-profile 0.2.1 
nucleus-dark-ui 0.12.3 
open-in-github-app 0.2.6 
php-debug 0.2.6 
pigments 0.40.2 
pretty-json 1.6.4 
remote-ftp 2.1.4 
sass-autocompile 0.13.5 
Sass-Syntax-Highlight 0.1.1 
spacegray-tomorrowdark-ui 2.1.0 
tag 0.5.0 
term3 0.22.1 
tomorrow-evening-syntax 1.1.0 
tomorrow-night-eighties 0.5.0 
tomorrow-night-eighties-syntax 1.0.2 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
unity-ui 2.1.11 
url-encode 0.5.0 
vagrant 0.1.0 
```

**Comment by mrkschan** [comment]
It seems that the error is actually raised by another package `my-github-profile` which also uses q.js according to the stacktrace

```
TypeError: Cannot read property 'repo_name' of undefined
    at StatusBarView.setProfile (/packages/my-github-profile/lib/main.coffee:57:62)
```

**Comment by shelbyKiraM** [comment]
Yeah, I opened one there, but "Latest commit `1ec7b4d` on Jul 12, 2015", I probably won't get a reply. Closing this ticket, though. Thanks!

**Comment by mrkschan** [comment]
@marv3lls i think it's an issue in https://github.com/atom/atom/ that provided a trace at the wrong package ... Would you be able to reproduce it with Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode ?
