### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of null

### ISSUE THREAD

**Issue by samppan** [mrkschan/ctags-status#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.9.5
**Thrown From**: [ctags-status](https://github.com/mrkschan/ctags-status) package, v1.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'find' of null

```
At /Users/sampan/.atom/packages/ctags-status/lib/ctags-status.coffee:95

TypeError: Cannot read property 'find' of null
  at /Users/sampan/.atom/packages/ctags-status/lib/ctags-status.coffee:95:22
  at Object.module.exports.CtagsStatus.toggle (/Users/sampan/.atom/packages/ctags-status/lib/ctags-status.coffee:132:7)
  at /Users/sampan/.atom/packages/ctags-status/lib/ctags-status.coffee:75:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1515:27)
  at /Applications/Atom.app/Contents/Resources/app/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/src/marker.js:265:22)
  at /Applications/Atom.app/Contents/Resources/app/src/marker.js:47:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:514:22)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:184:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/marker.js:172:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/marker.js:182:19)
  at /Applications/Atom.app/Contents/Resources/app/src/cursor.js:121:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:683:7)
  at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:119:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1306:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1506:9)
  at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1305:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:546:25)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:61)

```
### Commands

```
  3x -6:17.9 core:backspace (atom-text-editor.editor.mini)
     -6:17.1 core:confirm (atom-text-editor.editor.mini)
     -5:27.0 project-find:show (atom-text-editor.editor)
     -5:26.6 core:confirm (atom-text-editor.editor.mini)
  3x -5:22.9 project-find:show (atom-text-editor.editor)
     -4:52.8 core:confirm (atom-text-editor.editor.mini)
     -4:50.8 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -4:48.2 find-and-replace:show (atom-text-editor.editor)
     -4:47.4 core:confirm (atom-text-editor.editor.mini)
     -4:44.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -4:44.2 core:cancel (atom-text-editor.editor.mini)
  3x -4:22.4 settings-view:uninstall-packages (atom-text-editor.editor)
     -1:56.7 core:confirm (atom-text-editor.editor.mini)
  8x -0:55.7 core:move-up (atom-text-editor.editor)
  6x -0:53.7 core:move-down (atom-text-editor.editor)
     -0:11.1 settings-view:uninstall-packages (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "function-name-in-status-bar",
      "ctags-status"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-terminal, v0.7.0
autocomplete-plus, v2.10.0
linter, v0.12.0

# Dev
No dev packages
```

**Comment by mrkschan** [comment]
@samppan, i can confirm the reported issue can be reproduced by disabling this package and move the cursor around on the editor.
