### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ricsdeol** [mrkschan/ctags-status#9]
[Enter steps to reproduce below:]
1. Open a YML file!

**Atom Version**: 0.192.0
**System**: linux 3.16.0-34-generic
**Thrown From**: [ctags-status](https://github.com/mrkschan/ctags-status) package, v1.1.3
### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```

This error happened when I open YML file.
At /home/ricardoleite/.atom/packages/ctags-status/lib/scope-finder.coffee:15

TypeError: Cannot read property 'trim' of undefined
  at Object.module.exports.guessedTagEnd (/home/ricardoleite/.atom/packages/ctags-status/lib/scope-finder.coffee:15:21)
  at explode (/home/ricardoleite/.atom/packages/ctags-status/lib/ctags-status.coffee:124:27)
  at /home/ricardoleite/.atom/packages/ctags-status/lib/ctags-status.coffee:128:17
  at /home/ricardoleite/.atom/packages/ctags-status/lib/ctags-status.coffee:170:15
  at /home/ricardoleite/.atom/packages/ctags-status/lib/ctags.coffee:35:7
  at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:137:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```
### Commands

```
  2x -2:15.0 core:move-down (atom-text-editor.editor.mini)
     -2:13.8 core:confirm (atom-text-editor.editor.mini)
     -2:13.5 git-diff-popup:toggle (atom-text-editor.editor)
     -2:08.4 command-palette:toggle (atom-text-editor.editor)
  4x -2:06.1 core:backspace (atom-text-editor.editor.mini)
  5x -2:02.1 core:move-down (atom-text-editor.editor.mini)
  3x -2:00.5 core:move-up (atom-text-editor.editor.mini)
     -1:56.7 core:move-down (atom-text-editor.editor.mini)
     -1:55.9 core:confirm (atom-text-editor.editor.mini)
     -1:55.9 git-difftool:diff-file (atom-text-editor.editor)
     -1:42.4 command-palette:toggle (atom-text-editor.editor)
     -1:36.4 core:confirm (atom-text-editor.editor.mini)
     -1:35.6 git-plus:diff (atom-text-editor.editor)
     -0:46.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:02.3 core:backspace (atom-text-editor.editor.mini)
     -0:02.1 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "linter-erb",
      "symbols-view"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.24.1
atom-color-highlight, v3.0.8
atom-ctags, v2.6.1
atom-zeal, v0.1.0
atomatigit, v1.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
autocomplete-plus-async, v0.22.0
autocomplete-ruby, v0.1.0
autocomplete-snippets, v1.2.0
color-picker, v1.7.0
css-snippets, v0.7.0
ctags-status, v1.1.3
docs-snippets, v0.8.0
file-icons, v1.5.4
filetype-color, v0.1.4
git-diff-popup, v0.1.2
git-difftool, v0.2.5
git-log, v0.3.0
git-plus, v4.5.0
git-tab-status, v1.7.0
gulp-snippets, v0.6.1
html-id-class-snippets, v1.4.1
language-gitignore, v0.2.0
language-txt2tags, v0.3.0
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-haml, v0.1.1
linter-js-yaml, v1.0.0
linter-jshint, v0.1.2
linter-less, v0.3.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
linter-tidy, v1.0.0
local-history, v2.3.0
minimap, v4.7.6
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-selection, v4.2.0
related-files, v0.3.0
rspec-snippets, v0.4.0
ruby-block, v0.3.3
spotify-linux, v0.2.3
symbols-tree-view, v0.9.2
sync-settings, v0.2.2
tab-smart-sort, v0.1.2
wakatime, v4.0.2

# Dev
No dev packages
```

**Comment by mrkschan** [comment]
I tried opening some .yml file and that doesn't break anything. 

And, I was aware of this issue before with other file extension but cannot really find any re-produceable steps.

BTW, going to add guard against an empty Atom buffer.
